### ISSUE TITLE
Not downloading

### ISSUE THREAD

**Issue by benrap** [Khang-NT/Listen-2-Youtube#1]
I don't know if this is a fault in your app, or if it's the Xposed installer's fault, or possibly the xda server is faulty, but your app simply won't download from the installer. The animation is displayed (both in the app and in the notification), but in the app it says 'download is waiting". Maybe re upload the app?

**Comment by AmineIzumi** [comment]
Same here sadly.

**Comment by Khang-NT** [comment]
Sorry guys, I'm using Heroku cloud for my app and it's only active 16 hours per day, It look like the traffic starting more heavy. I think it can work correctly in almost time, I will upgrade my server soon. You can also use my cloud app easily:
Get link (text/plain response):
https://murmuring-brushlands-18762.herokuapp.com/?id=[Video_id]&type=link
or redirect google host (some time not work with famous video, ip blocked by youtube):
https://murmuring-brushlands-18762.herokuapp.com/?id=[Video_id]&type=redirect
or play it directly (speed is quite slow):
https://murmuring-brushlands-18762.herokuapp.com/?id=[Video_id]

**Comment by AmineIzumi** [comment]
Isn't there any other way to download the apk ? On Google Drive for example ?

**Comment by Khang-NT** [comment]
Oh, this is my mistake, I read quickly and understand wrong, I thought it's problem of my app when download youtube DASH audio.

I fixed download link:
https://drive.google.com/file/d/0Byh8ZvMluYzDSFB0YjB6ajV1d0U/view?usp=sharing
It about ~60MB because it include all cpu available supporting. 
You can download source and compile by your self with speciality device, and apk file's size will be lower.

**Comment by benrap** [comment]
Ahhh you just updated the app on xposed installer and still there is a problem. This time there is an install error. Please fix this. Plus, i installed the apk from the link you gave and it isn't an xposed module. What exactly is this app supposed to do? I understood it's supposed to enable playing audio - only on youtube, and downloading the audio too

**Comment by tonylost** [comment]
Please fix:
Unable to install as a Xposed module.
Xposed not recognize the module.
Downlading from Xposed repository say: "MD5 Checksum Error"
A smaller file size for each architecture. (Compiling separately.)
can it be? ;)

**Comment by Khang-NT** [comment]
See my new updates guys. :+1: 
fixed Khang-NT/Listen-2-Youtube#1

**Comment by benrap** [comment]
Still get an error "download file is not an apk". What the heck is goin' with this app?
